[package]
name = "validator"
version = "0.1.0"
edition = "2021"

[dependencies]
openapiv3 = "1.0.2"
serde_yaml = "0.9.17"
serde_json = "1.0.94"
indexmap = "1.9.3"
jsonschema = "0.17.0"
url = "2.4.0"
regex = "1.9.1"

[dev-dependencies]
parameterized = "1.0.1"
indoc = "2.0.0"
reqwest = "0.11.24"