openapi: 3.0.0

info:
  description: API to handle generic two-way HTTP requests
  version: "1.0.0"
  title: Swagger ReST Article

paths:
  /ping:
    get:
      summary: Ping
      responses:
        200:
          description: API call successful

  /multiple/allowed/operations:
    put:
      summary: Allows put operation
      responses:
        200:
          description: API call successful
    delete:
      summary: Allows delete operation
      responses:
        200:
          description: API call successful
    post:
      summary: Allows post operation
      responses:
        200:
          description: API call successful

  /required/body:
    post:
      summary: Requires a body
      requestBody:
        required: true
      responses:
        200:
          description: API call successful

  /not/required/body:
    post:
      summary: Requires a body
      requestBody:
        required: false
      responses:
        200:
          description: API call successful
